=== searothonc/Tikubiken/dtd/tikubiken_diff100.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--############################################################-->
<!--  Tikubiken diff XML definition                             -->
<!--  Version 1.00                                              -->
<!--  2021-10-30                                                -->
<!--  Copyright (c) Searothonc                                  -->
<!--############################################################-->

<!--////////////////////////////////////////////////////////////-->
<!--  <Tikubiken>                                               -->
<!--////////////////////////////////////////////////////////////-->
<!ELEMENT Tikubiken (updater?, patch*, install+) >
<!ATTLIST Tikubiken version (1.00) #IMPLIED >
<!ATTLIST Tikubiken format  CDATA #FIXED "diff" >


<!--////////////////////////////////////////////////////////////-->
<!--  <updater>                                                 -->
<!--////////////////////////////////////////////////////////////-->
<!ELEMENT updater (cover|title|localise|layout)* >

<!--==============================-->
<!--  <cover>                     -->
<!--==============================-->
<!ELEMENT cover EMPTY>
<!ATTLIST cover image CDATA #REQUIRED>
<!ATTLIST cover lang  CDATA #IMPLIED>

<!--==============================-->
<!--  <title>                     -->
<!--==============================-->
<!ELEMENT title EMPTY>
<!ATTLIST title text  CDATA #REQUIRED>
<!ATTLIST title lang  CDATA #IMPLIED><!-- IETF language tag RFC 5646 -->

<!--==============================-->
<!--  <localise>                  -->
<!--==============================-->
<!ELEMENT localise (#PCDATA)>
<!ATTLIST localise target (progress|start|cancel|exit|processing) #REQUIRED>
<!ATTLIST localise lang   CDATA #REQUIRED><!-- IETF language tag RFC 5646 -->

<!--==============================-->
<!--  <layout>                    -->
<!--==============================-->
<!ELEMENT layout (anchor|autosize|location|size)* >
<!ATTLIST layout target (form|pictureBox|labelMessage|buttonStart|labelProgress|progressBar) "form">

<!--==============================-->
<!--  <autosize>                  -->
<!--==============================-->
<!ELEMENT autosize EMPTY>
<!ATTLIST autosize value  (true|false) #REQUIRED>

<!--==============================-->
<!--  <anchor>                    -->
<!--==============================-->
<!ELEMENT anchor EMPTY>
<!ATTLIST anchor styles ENTITIES #REQUIRED>
<!NOTATION  AnchorStyles  SYSTEM  "AnchorStyles">
<!ENTITY  None    SYSTEM  "None=0"    NDATA AnchorStyles>
<!ENTITY  Top     SYSTEM  "Top=1"     NDATA AnchorStyles>
<!ENTITY  Bottom  SYSTEM  "Bottom=2"  NDATA AnchorStyles>
<!ENTITY  Left    SYSTEM  "Left=4"    NDATA AnchorStyles>
<!ENTITY  Right   SYSTEM  "Right=8"   NDATA AnchorStyles>

<!--==============================-->
<!--  <location>                  -->
<!--==============================-->
<!ELEMENT location EMPTY>
<!ATTLIST location x  CDATA #REQUIRED>
<!ATTLIST location y  CDATA #REQUIRED>

<!--==============================-->
<!--  <size>                      -->
<!--==============================-->
<!ELEMENT size EMPTY>
<!ATTLIST size width  CDATA #REQUIRED>
<!ATTLIST size height CDATA #REQUIRED>


<!--////////////////////////////////////////////////////////////-->
<!--  <patch>                                                   -->
<!--////////////////////////////////////////////////////////////-->
<!ELEMENT patch (branch,target) >
<!ATTLIST patch version ID    #REQUIRED>

<!--==============================-->
<!--  <branch>                    -->
<!--==============================-->
<!ELEMENT branch  (exclude)*>
<!ATTLIST branch path CDATA #REQUIRED>

<!--==============================-->
<!--  <target>                    -->
<!--==============================-->
<!ELEMENT target  (exclude)*>
<!ATTLIST target path CDATA #REQUIRED>

<!--==============================-->
<!--  <exclude>                   -->
<!--==============================-->
<!ELEMENT exclude EMPTY>
<!ATTLIST exclude name   CDATA #REQUIRED>
<!ATTLIST exclude match  (exact|wildcard|regex) "wildcard">


<!--////////////////////////////////////////////////////////////-->
<!--  <install>                                                 -->
<!--////////////////////////////////////////////////////////////-->
<!ELEMENT install (registry?, identity+) >

<!--==============================-->
<!--  <registry>                  -->
<!--==============================-->
<!ELEMENT registry  EMPTY>
<!ATTLIST registry root   (HKEY_CLASSES_ROOT|HKEY_CURRENT_USER|HKEY_LOCAL_MACHINE|HKEY_CURRENT_CONFIG|HKEY_USERS|HKCR|HKCU|HKLM|HKCC|HKU) #REQUIRED>
<!ATTLIST registry subkey CDATA #REQUIRED>
<!ATTLIST registry value  CDATA #REQUIRED>


<!--////////////////////////////////////////////////////////////-->
<!--  <identity>                                                -->
<!--////////////////////////////////////////////////////////////-->
<!ELEMENT identity  ((patch|patchref), message?) >
<!ATTLIST identity path   CDATA #REQUIRED>
<!ATTLIST identity method (MD5|SHA1) "SHA1">

<!--==============================-->
<!--  <patchref>                  -->
<!--==============================-->
<!ELEMENT patchref EMPTY>
<!ATTLIST patchref version IDREF #REQUIRED>


<!--////////////////////////////////////////////////////////////-->
<!--  <message>                                                 -->
<!--////////////////////////////////////////////////////////////-->
<!ELEMENT message (text*)>

<!--==============================-->
<!--  <text>                      -->
<!--==============================-->
<!ELEMENT text (#PCDATA|br)*>
<!ATTLIST text lang NMTOKEN #IMPLIED><!-- IETF language tag RFC 5646 -->
<!ATTLIST text type (ready|process|complete|cancel|title|error|err_misplace|err_shortspace|err_newest) "ready">

<!--==============================-->
<!--  <br/>                       -->
<!--==============================-->
<!ELEMENT br  EMPTY>

=== searothonc/Tikubiken/sample_en.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
Sample XML document of Tikubiken
Ver1.0 Copyright (c) 2021 Searothonc

This file is distributed under CC0 license(public domain). 
Feel free to copy, modify and reprint for your own purpose.
-->
<!DOCTYPE Tikubiken SYSTEM "http://raw.githubusercontent.com/searothonc/Tikubiken/master/dtd/tikubiken_diff100.dtd" [
  <!ENTITY  path_cover_images   "..\tikubiken\cover_images">
  <!ENTITY  path_deploy_target  "..\Deployments">
  <!ENTITY  path_deploy_source  ".\old_versions">

  <!-- Common messages -->
  <!ENTITY  en_cancel     "Update aborted. Please close the application.">
  <!ENTITY  en_error      "No update was made because some errors occurred.">
  <!ENTITY  en_misplace   "Failed to find the installed files to apply updates. Please place this program in the folder where the game has been installed and then restart.">
  <!ENTITY  en_shortspace "Insufficient free space on the destination drive.">
  <!ENTITY  en_newest     "There is no need to update because the installed version is already newest.">

  <!ENTITY  jp_cancel     "アップデートを中止しました。アプリケーションを終了してください。">
  <!ENTITY  jp_error      "エラーが発生したため更新は行われませんでした。">
  <!ENTITY  jp_misplace   "更新を適用するインストール済ファイルが見つかりません。本プログラムをインストール先のフォルダに配置して起動して下さい。">
  <!ENTITY  jp_shortspace "インストール先ドライブの空き容量が足りません。">
  <!ENTITY  jp_newest     "インストール済みのバージョンは既に最新版のためアップデートの必要はありません。">
]>
<!--●XML declaration(<?xml ...>) and DOCTYPE declaration
Declares that this file is an XML document and that tag structure follows 
the DTD specified by <!DOCTYPE>.
It's kind of like a magic spell, so just write the following and it will 
work fine:

  <?xml version="1.0" encoding="UTF-8" ?>
  <!DOCTYPE Tikubiken SYSTEM "http://raw.githubusercontent.com/searothonc/Tikubiken/master/dtd/tikubiken_diff100.dtd">

The character encoding used in this file must be UTF-8 as specified in 
the "encoding" attribute of XML declaration.
-->
<!--●Entity references
The entity reference is the same function that is used in HTML 
to replace "&gt;" and "&lt;" with "<" and ">".
The DTD of Tikubiken does not define any additional entity references, 
so only XML's predefined defalut entities are available 
if you do not define any further.
    ▽Default XML predefined entities
      Literal         Outpt
      &quot;          "
      &amp;           &
      &apos;          '
      &lt;            <
      &gt;            >
For example, if you want to use whitespace in <text> elements, etc. as in HTML, 
you need to add entities definition in the XML document like below:
    ▽Example
    <!DOCTYPE Tikubiken SYSTEM "https://raw.../tikubiken_diff100.xml" [
      <!ENTITY  nbsp    " ">
      <!ENTITY  emsp    "　">
    ]>
In the case you write the DOCTYPE declaration as above, 
&nbsp; will be converted to a half-width space, and &emsp; to a full-width space.

As shown in this sample XML, entity references can be used to replace 
a variety of strings, such as recurring terms or paths to folders.
-->

<!--●Specifying file paths
The file path can be specified as an absolute or relative path.
Unless otherwise indicated, the relative path will be based 
from the folder where the xml document is located.
-->

<!--●IETF language tags
For elements that define the same meaning for multiple languages (title, 
cover, text, etc.), the "lang" attribute specifies the target language.
Multi-language support is achieved by adopting the element which matches 
the "lang" attribute.
The "lang" attributes are basically specified by IETF language tag = the form 
often seen on the internet such as ja-JP or en-US.

  IETF language tag - Wikipedia
  https://en.wikipedia.org/wiki/IETF_language_tag

Up to the length of the string specified by the "lang" attribute will be 
compared, and if the full text matches, the element will be adopted. 
If the language name of the current locale is longer than the "lang" attribute 
value, the rest of the string is ignored. 
So, for example, if you want to specify all English regardless of nationality, 
"en" or "en-" will all match "en-US", "en-UK", "en-AU", "en-CA", etc.

  List of ISO 639-1 codes - Wikipedia
  https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

If there is no match with any "lang" attribute, 
the element with no "lang" attribute will be used as the default value.
-->

<!--●<Tikubiken> Element
‣ The root element of the XML document. Only the first letter T is capitalized, 
  the rest are lowercase.
  ⁃ Note that xml is case-sensitive. If you use <tikubiken>, you will get an 
    error.
  ⁃ In the Tikubiken XML document type, only the root element has an uppercase 
    initial letter, all other child elements are entirely lowercase.
‣ The "format" attribute is required, and the value is fixed to "diff".
‣ The first child element is fixed to <updater>. Optional.
‣ Place an arbitrary number (including zero) of <patch> elements as the second 
  and subsequent elements. Next, place one or more <install> elements of 
  any number.
  ⁃ This order cannot be swapped.
  ⁃ The <patch> element can also be specified directly in the <install> 
    element,    so it does not have to be placed if it is not needed.
-->
<Tikubiken format="diff">

  <!--●<updater> element
  ‣ The element that define the appearance of the updater program.
  ‣ No attributes.
  ‣ It can have any number of <cover> and <title> elements as child 
    elements (optional).
  ▼<title> elements
  ‣ Specify the window caption in the title bar of the updater program.
  ‣ If omitted, "Updater" will be used as the default value.
  ‣ The "text" attribute is required and specifies the string to be displayed 
    in the title bar. 
  ‣ The "lang" attribute can be specified optionally, and is used to specify 
    the IETF language tag (ja-JP, en-US, etc.).
  ‣ The title specified by the <title> element is also reflected in the title 
    bar of the message box displayed in case of errors. In this case, the width 
    of the title bar is shorter than the main window, so it is recommended to 
    specify a shorter title.
  ‣ The title bar of the main window will be overwritten if a <text type="title"> 
    tag is specified later in the <message> tag. If you need a more detailed 
    title, specify it with <text type="title">.
  ▼<cover> elements
  ‣ Specify the banner image to be displayed in the updater program window.
  ‣ If omitted, the default image will be displayed.
  ‣ The "image" attribute is required and specifies the path to the image file.
    ⁃ The minimum size of image is 480x64 and the window will expand to fit 
      to the image size.
    ⁃ All image formats supported by .NET can be used.
      (BMP/JPG/GIF/PNG/EXIG/TIFF/WMF/EMF)
  ‣ The "lang" attribute can be specified optionally, and is used to specify 
    the IETF language tag (ja-JP, en-US, etc.).
  ▼<localise> elements
  ‣ The elements that make the content displayed in the window of the Updater 
    program multilingual.
  ‣ The "target" attribute is required and specifies the target to be 
    multilingualized.
    ⁃ The value can be specified as one of "progress", "start", "cancel", 
      "exit", or "processing".
    ⁃ If the "target" attribute is "progress", the content is the text displayed 
      in the label attached to the progress bar
    ⁃ If "target" attribute is "start", the content is the text displayed 
      on the [Start] button
    ⁃ If "target" attribute is "cancel", the content is the text displayed 
      on the [Cancel] button
    ⁃ If "target" attribute is "exit", the content is the text displayed 
      on the [Exit] button
    ⁃ If the "target" attribute is "processing", the content is the text 
      displayed on the button that cannot be pressed while processing.
    ⁃ As in &amp;X, uou can specify a mnemonic (shortcut key to move keyboard 
      focus) by placing &amp; in front of the alphabet.
  ‣ Unlike other elements, the <localise> element requires the "lang" attribute, 
    which specifies the target language in IETF language tags(ja-JP, en-US..).
  ‣ Specifies a translated string in the element's content text. Whitespaces 
    before and after characters are removed and line breaks are ignored.
  -->
  <updater>
    <title text="&quot;Virgin&apos;s Protection Magic&quot; updater"/>
    <title text="『処女を守る魔法』アップデータ" lang="ja"/>

    <!-- Example of entity reference application: the files specified in these two <cover> elements are in the same folder -->
    <cover image=".\tikubiken\cover_images\cover-640x160-en.png"/>
    <cover image="&path_cover_images;\cover-640x160-jp.png" lang="ja"/>

    <localise target="progress" lang="ja">進捗状況</localise><!-- "Progress" for default -->
    <localise target="start" lang="ja">アップデート開始(&amp;S)</localise>
    <localise target="start" lang="en">&amp;Start updating</localise>
    <localise target="cancel" lang="ja">キャンセル(&amp;C)</localise>
    <localise target="exit" lang="ja">終了(&amp;E)</localise>
    <localise target="processing" lang="ja">処理中...</localise>

    <!--●<layout> elements
    ‣ Override the properties of a Windows form control to change its layout.
    ‣ Usually there is no need to use these tags at all.
    ‣ Specify the control to be changed in the "target" attribute 
      and set the corresponding property 
      in the child element <location><size><anchor><autosize>.
    ‣ Since setting this up requires knowledge of Windows Forms, a detailed 
      explanation is omitted here.
    ‣ The default values for the case where the layout is not changed are 
      listed below in the comments. Only the values listed below can be changed.
    -->
    <!--
    <layout target="form">
      <autosize value="true"/>
      <size width="512" height="320"/>
    </layout>
    <layout target="pictureBox">
      <anchor styles="Top Bottom Left Right"/>
